### ISSUE TITLE
Displaying all possible routes for a bus system

### ISSUE THREAD

**Issue by dcunited001** [conveyal/transitive.js#22]
So, my team worked on a project for a hackathon this past weekend where we were planning on mapping data from GTFS and displaying it in a leaflet map with transitive.  You can view our code [here](https://github.com/dcunited001/noke-codes-ride-solutions/tree/master/gtfs-to-transitive).  

The GTFS data that's been converted to the transitive format is already in the repository, so all you really have to do is `component install && component build` and open index.html in a browser.  In `index.js`, I'm trying to plot 3 of the bus routes as journeys, but something goes wrong, when the path segments are put together and the path segments have no points.

Can you tell me if this is something that's possible with Transitive?  What our bus system is looking for is a stylized interactive map of the bus system and the transitive design looks perfect.  Another big thing we were hoping to deliver was uploading the GTFS data to OSM Transport.

**Comment by nathanv** [comment]
:+1:

**Comment by derhuerst** [comment]
@dcunited001 Did you find a solution to the documented problems?
If you did, can you share them?

**Comment by dcunited001** [comment]
@derhuerst Sorry i don't think I did. Are you experiencing something that sounds similar? 

I'm trying to review the state of our project, but i think this is about the last thing we got to. The gist at the time was that it was going to require some custom work or at least a deep dive into the transitive.js source. I think.

It looks like there have been many changes to the transitive.js project since then. At the time, some of the Conveyal/Transitive projects were a bit tough to get running, but did run. 

If you have other specific questions, it may jog my memory a bit, but I'm not sure that I can help much with the current state of their projects.

**Comment by benda18** [comment]
> In `index.js`, I'm trying to plot 3 of the bus routes as journeys, but something goes wrong, when the path segments are put together and the path segments have no points.
> 
> Can you tell me if this is something that's possible with Transitive? What our bus system is looking for is a stylized interactive map of the bus system and the transitive design looks perfect. Another big thing we were hoping to deliver was uploading the GTFS data to OSM Transport.

I have next to no experience with transitive but have been working with static GTFS feeds professionally since 2008.  Here's my guess about what's going on and how I'd solve the problem (in 3 parts): 

**_Part 1: Possible Problems_**
**Possible Problem 1**: The route paths data (i.e. the geographic representation of each trip_id) is stored in [shapes.txt](https://developers.google.com/transit/gtfs/reference#shapestxt), and this text file has always been an optional component of the static feed.   Furthermore, even if your feed has a shapes.txt file it's will still validate even if some trip_ids don't have an associated shape_id.  If you're wanting to check data quality, I'd start here first and just confirm that you can map all of your shapes outside of transitive. 

**Possible Problem 2**:  A GTFS feed will validate even if the feed specification isn't used exactly as intended.  I've seen schedulers get frustrated and just hammer away until the feed works.  This happens most often in calendar.txt and calendar_dates.txt, but also in trips.txt.  Occasionally these deviations exceed the designed functionality of the feed specification, and while the trip planning functionality works fine, 3rd party feed users like data professionals or developers - who are often trying to add useful features on top of the feed specification - realize they now have to build in like 5 or 10 different exceptions because of these differences that show up.    

I've been working with GTFS feeds from the perspective of a data professional throughout my career and almost every single feed I look at requires a custom script to clean/tidy the data to get it to the point where I can compare it to any other agency feed.  Even within a single agency, software changes and feed exports evolve and you may have to have different logic to account for old feeds vs. new feeds.  I can't imagine how complex this would be for someone like conveyal who is making open-source tools like transitive.  

**How I would approach this roadblock**: 
I don't know exactly what your project is, but I would just drop transitive completely and build something up in python or R.  Here's how i've come to think about the workflow of breaking down a GTFS feed logically: 

**_PART 2: Processing the GTFS Data_**: 
Step 1: pick a date (i.e. 10/31/2023)
Step 2: find the 1 or more service_ids that cover service on this date from within calendar.txt and/or calendar_dates.txt
Step 3: filter trips.txt down to just the trip_ids that have the service_id from Step 2. trips.txt has trip_name information. 
Step 4: join routes.txt to trips.txt by "route_id"; now you have route name information with every trip.  In R i would do `left_join(trips.txt, route.txt, by = "route_id")`
Step 5: join stops_times.txt to your output from Step 4 above by "trip_id".  Now you have a dataset that shows where and when each trip on each route travels between / to each stop throughout a single day of service. 
Step 6: join stops.txt to your output from Step 5 above by "stop_id."  Now you have lon/lat coordinates for every stop. 

At this point you have enough data to build a time lapse animation of the entire day's service based on which stops are being utilized by buses.  But you don't have any lines to show where each route travels.  You have a couple of different options for building out that basemap, but I think the easiest is as follows (shown in R):
```
routemap.df <- left_join(Step_6_output, 
          shapes.txt, 
          by = "shape_id") %>%
  group_by(route_id, trip_id, shape_id,
           route_name, trip_name, 
           shape_pt_sequence,
           shape_pt_lon, shape_pt_lat) %>%
  summarise()
```

**_PART 3: Presenting the Processed Data_**: 

Again, this is going to be focused on R because that's what I work in, but I would probably create a simple [shiny](https://www.rstudio.com/products/shiny/) dashboard with a map that is not interactive (I personally haven't learned how to work in leaflet yet, but maybe you have and this part is easy for you???).  Here are some of the libraries I would probably have to lean on to make this implementation work: 

ggmap --> specifically for get_stamenmap() for use as the map base layer
gganimate --> used to animate the change in the transit network throughout the day
shiny --> obviously to build the dashboard

Other libraries that you're probably going to need: 
lubridate --> for working with dates and times
ggplot2 --> for the plotting of the rest of the map layers

I hope this helped somewhat.
